version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./config/:/app/config/:ro
    networks:
      - drogon_jwt_postgres

networks:
  drogon_jwt_postgres:
    driver: bridge